name: 生成 插件市场所需 索引

on:
  push:
    paths:
      - 'Adapter/**'
      - 'plugins/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v2

      - name: 设置 Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: 安装依赖
        run: |
          cd .github/workflows
          npm install

      - name: 由Actions自动生成插件市场所需JSON索引
        run: |
          cd .github/workflows
          node generate_index.js

      - name: 检查生成的文件
        run: 'test -f publicFileIndex.json || echo "Error: publicFileIndex.json not found"'

      - name: 检查是否有更改
        id: changes
        run: |
          git add publicFileIndex.json
          if git diff --cached --quiet; then
            echo "::set-output name=has_changes::false"
          else
            echo "::set-output name=has_changes::true"
          fi

      - name: 提交并推送更改
        if: steps.changes.outputs.has_changes == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git commit -m '由Actions自动生成插件市场所需JSON索引'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
